// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: processor_message.proto

package laptop

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name               string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brand              string  `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Cores              uint32  `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads            uint32  `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	ClockSpeedGhz      float32 `protobuf:"fixed32,5,opt,name=clock_speed_ghz,json=clockSpeedGhz,proto3" json:"clock_speed_ghz,omitempty"`
	BoostClockSpeedGhz float32 `protobuf:"fixed32,6,opt,name=boost_clock_speed_ghz,json=boostClockSpeedGhz,proto3" json:"boost_clock_speed_ghz,omitempty"`
	TdpW               uint32  `protobuf:"varint,7,opt,name=tdp_w,json=tdpW,proto3" json:"tdp_w,omitempty"`
	CacheMb            uint32  `protobuf:"varint,8,opt,name=cache_mb,json=cacheMb,proto3" json:"cache_mb,omitempty"`
}

func (x *CPU) Reset() {
	*x = CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_processor_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_processor_message_proto_rawDescGZIP(), []int{0}
}

func (x *CPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CPU) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPU) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPU) GetClockSpeedGhz() float32 {
	if x != nil {
		return x.ClockSpeedGhz
	}
	return 0
}

func (x *CPU) GetBoostClockSpeedGhz() float32 {
	if x != nil {
		return x.BoostClockSpeedGhz
	}
	return 0
}

func (x *CPU) GetTdpW() uint32 {
	if x != nil {
		return x.TdpW
	}
	return 0
}

func (x *CPU) GetCacheMb() uint32 {
	if x != nil {
		return x.CacheMb
	}
	return 0
}

type GPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name               string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brand              string  `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	ClockSpeedGhz      float32 `protobuf:"fixed32,3,opt,name=clock_speed_ghz,json=clockSpeedGhz,proto3" json:"clock_speed_ghz,omitempty"`
	BoostClockSpeedGhz float32 `protobuf:"fixed32,4,opt,name=boost_clock_speed_ghz,json=boostClockSpeedGhz,proto3" json:"boost_clock_speed_ghz,omitempty"`
	Memory             *Memory `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *GPU) Reset() {
	*x = GPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_processor_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_processor_message_proto_rawDescGZIP(), []int{1}
}

func (x *GPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GPU) GetClockSpeedGhz() float32 {
	if x != nil {
		return x.ClockSpeedGhz
	}
	return 0
}

func (x *GPU) GetBoostClockSpeedGhz() float32 {
	if x != nil {
		return x.BoostClockSpeedGhz
	}
	return 0
}

func (x *GPU) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_processor_message_proto protoreflect.FileDescriptor

var file_processor_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x63, 0x62, 0x6f, 0x6f,
	0x6b, 0x1a, 0x14, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x70, 0x65, 0x65, 0x64, 0x47, 0x68,
	0x7a, 0x12, 0x31, 0x0a, 0x15, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x73, 0x70, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x12, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x47, 0x68, 0x7a, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x64, 0x70, 0x5f, 0x77, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x64, 0x70, 0x57, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x6d, 0x62, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x4d, 0x62, 0x22, 0xb2, 0x01, 0x0a, 0x03, 0x47, 0x50, 0x55, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0d, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x70, 0x65, 0x65, 0x64, 0x47, 0x68, 0x7a, 0x12, 0x31,
	0x0a, 0x15, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12, 0x62,
	0x6f, 0x6f, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x70, 0x65, 0x65, 0x64, 0x47, 0x68,
	0x7a, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x75, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x6c, 0x61,
	0x70, 0x74, 0x6f, 0x70, 0x2f, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_processor_message_proto_rawDescOnce sync.Once
	file_processor_message_proto_rawDescData = file_processor_message_proto_rawDesc
)

func file_processor_message_proto_rawDescGZIP() []byte {
	file_processor_message_proto_rawDescOnce.Do(func() {
		file_processor_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_processor_message_proto_rawDescData)
	})
	return file_processor_message_proto_rawDescData
}

var file_processor_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_processor_message_proto_goTypes = []interface{}{
	(*CPU)(nil),    // 0: pcbook.CPU
	(*GPU)(nil),    // 1: pcbook.GPU
	(*Memory)(nil), // 2: pcbook.Memory
}
var file_processor_message_proto_depIdxs = []int32{
	2, // 0: pcbook.GPU.memory:type_name -> pcbook.Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_processor_message_proto_init() }
func file_processor_message_proto_init() {
	if File_processor_message_proto != nil {
		return
	}
	file_memory_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_processor_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_processor_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_processor_message_proto_goTypes,
		DependencyIndexes: file_processor_message_proto_depIdxs,
		MessageInfos:      file_processor_message_proto_msgTypes,
	}.Build()
	File_processor_message_proto = out.File
	file_processor_message_proto_rawDesc = nil
	file_processor_message_proto_goTypes = nil
	file_processor_message_proto_depIdxs = nil
}
